center:
  x: -34.615
  y: -58.450
zoom: 11
marker_shadow_url: "icons/category-shadow.svg"
marker_editable_url: "icons/category-editable.svg"
style: "mapbox.streets"
geometry_styles:
  polyline:
    shapeOptions:
      clickable: false
      color: "#FF5A5A"
      weight: 2
      className: "polyline"
  polygon:
    allowIntersection: false
    drawError:
      color: "#FF5A5A"
      message: "<strong>Oh snap!<strong> you can't draw that!"
    shapeOptions:
      clickable: false
      color: "#FF5A5A"
      weight: 2
      className: "polygon"
  rectangle:
    shapeOptions:
      clickable: false
  circle:
    shapeOptions:
      clickable: false
  marker:
      shapeOptions:
      clickable: false
      icon:
        iconSize: [40, 40]
        iconAnchor: [20, 30]
        className: "marker"
        shadowSize: [40, 40]
        shadowAnchor: [19, 29]
  circlemarker:
      shapeOptions:
        clickable: false
